# Generated by Django 2.2 on 2019-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cityname', models.CharField(default='unlisted', max_length=50)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField(null=True)),
                ('condition', models.CharField(default='no condition listed', max_length=50)),
                ('cond_code', models.IntegerField()),
                ('long_desc', models.CharField(default='no long description given', max_length=80)),
                ('sunrise', models.IntegerField(null=True)),
                ('sunset', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
