# Generated by Django 2.2 on 2019-11-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statelog',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logloc', to='backend.Location'),
        ),
        migrations.CreateModel(
            name='RangeSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField(default=float("-inf"))),
                ('max', models.FloatField(default=float("inf"))),
                ('representative', models.FloatField()),
                ('count', models.IntegerField(default=0)),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Device')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ColorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('rgb', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Capability')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Device')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Parameter')),
            ],
        ),
    ]
