# Generated by Django 2.2 on 2020-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bincounter_colorcounter_counter_rangecounter_setcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('typ', models.TextField(choices=[('syn_first', 'First Time Synthesize'), ('syn_followup', 'Following-Up Synthesize'), ('debug_first', 'First Time Debug'), ('debug_followup', 'Following-Up Debug'), ('edit_rule', 'Edit Rule')])),
            ],
        ),
    ]
