# Generated by Django 2.2 on 2020-03-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
    ]
