"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 2.0.2.
For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os, sys

from celery.schedules import crontab

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'corsheaders',
    'user_auth',
    'backend',
    'autotap',
    'django_celery_beat',
    'currentweather.apps.CurrentweatherConfig',
    'celery_workers.apps.CeleryWorkersConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'iot-tap-backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iot-tap-backend.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'iot-tap-backend.auth_backend.IoTCoreAuthBackend',
    'django.contrib.auth.backends.ModelBackend'
]

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/backend/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# to ensure that csrf token will be saved in cookies
CSRF_USE_SESSIONS = False

CSRF_TRUSTED_ORIGINS = [
    'superifttt.cs.uchicago.edu',
    'api.superifttt.cs.uchicago.edu'
]


CORS_ORIGIN_ALLOW_ALL = False

# allow cookies for cross-site HTTP request
CORS_ALLOW_CREDENTIALS = True

PROJECT_NAME = "superifttt"

GLOBAL_SETTINGS = {
    "DEFAULT_STAPP_PERMISSIONS": ["r:devices:*", "x:devices:*", "r:locations:*", "i:deviceprofiles:*"],
    "DEFAULT_STAPP_DEBRIEFING": "The app is going to collect the usage of all your smart devices. The collected data will be used for research purpose only.",
    "DEFAULT_PROD_ENDPOINT": "https://apicore.superifttt.cs.uchicago.edu/",
    "DEFAULT_DEBUG_ENDPOINT": "http://localhost:8000/",
    "DEFAULT_DOCKER_ENDPOINT": "http://backend:8000/"
}

VIRTUAL_DEVS = {
    "Weather": ["Current Temperature", "Relative Humidity Measurement", "Weather Sensor"], 
    "Clock": ["Clock", "Time Since State"]
}

IOTCORE_URL = 'http://iotcore:8001/iotcore/'
IOTCORE_VD_URL = 'http://iotcore:8001/vd/'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'ifttt_cache_table',
        'TIMEOUT': 1800
    },
    'trace': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'ifttt_cache_trace',
        'TIMEOUT': None
    }
}


# Configurations of the synthesizer
PRE_TIME = 15 * 60
POST_TIME = 2 * 60
LEARNING_RATE_SYN = 0.3

VIS_DEBUG = 2 * 60