from django.contrib import admin
import backend.models as m

# Register your models here.
admin.site.register(m.UserProfile)
admin.site.register(m.User_ICSE19)
admin.site.register(m.Channel)
admin.site.register(m.Capability)
admin.site.register(m.Parameter)
admin.site.register(m.SetParam)
admin.site.register(m.SetParamOpt)
admin.site.register(m.RangeParam)
admin.site.register(m.BinParam)
admin.site.register(m.ColorParam)
admin.site.register(m.TimeParam)
admin.site.register(m.DurationParam)
admin.site.register(m.InputParam)
admin.site.register(m.MetaParam)
admin.site.register(m.ParVal)
admin.site.register(m.ActionParVal)
admin.site.register(m.Condition)
admin.site.register(m.Device)
admin.site.register(m.State)
admin.site.register(m.Trigger)
admin.site.register(m.Rule)
admin.site.register(m.ESRule)
admin.site.register(m.SSRule)
admin.site.register(m.SafetyProp)
admin.site.register(m.SP1)
admin.site.register(m.SP2)
admin.site.register(m.SP3)
admin.site.register(m.StateLog)
admin.site.register(m.Location)
admin.site.register(m.ErrorLog)
admin.site.register(m.STCapability)
admin.site.register(m.Action)
admin.site.register(m.ActionCondition)
admin.site.register(m.ParValMapping)
admin.site.register(m.LocationVirtualDevices)
admin.site.register(m.Counter)
admin.site.register(m.BinCounter)
admin.site.register(m.SetCounter)
admin.site.register(m.RangeCounter)
admin.site.register(m.ColorCounter)
admin.site.register(m.Record)
