# Generated by Django 2.0.8 on 2018-10-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartthings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('capabilities', models.ManyToManyField(to='smartthings.Capability')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.Capability'),
        ),
        migrations.AddField(
            model_name='argument',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.Command'),
        ),
    ]
