# Generated by Django 2.0.8 on 2018-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0002_auto_20181002_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.TextField(default=None, null=True),
        ),
    ]
