# Generated by Django 2.0.8 on 2018-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0003_auto_20181009_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='st_device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.AddField(
            model_name='device',
            name='proj_device_id',
            field=models.IntegerField(default=-1),
        ),
    ]
