# Generated by Django 2.0.8 on 2018-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0004_auto_20181009_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='data_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='argument',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='st_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
