# Generated by Django 2.0.8 on 2018-10-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0005_auto_20181010_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='STAppConfPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=128)),
                ('nextPageId', models.CharField(default=None, max_length=36, null=True)),
                ('previousPageId', models.CharField(default=None, max_length=36, null=True)),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='STAppConfSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='smartthings.STAppConfPage')),
            ],
        ),
        migrations.CreateModel(
            name='STAppConfSectionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.CharField(max_length=36)),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('setting_type', models.CharField(max_length=36)),
                ('required', models.BooleanField(default=True)),
                ('multiple', models.BooleanField(default=False)),
                ('capabilities', models.ManyToManyField(to='smartthings.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='STAppInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_installed_app_id', models.CharField(max_length=36)),
                ('refresh_token', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='STAppPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='stapp',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='stapp',
            name='st_installed_app_id',
        ),
        migrations.AddField(
            model_name='stapp',
            name='app_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='stapp',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stapp',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='stappinstance',
            name='st_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.STApp'),
        ),
        migrations.AddField(
            model_name='stappconfsectionsetting',
            name='permissions',
            field=models.ManyToManyField(to='smartthings.STAppPermission'),
        ),
        migrations.AddField(
            model_name='stappconfsectionsetting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='smartthings.STAppConfSection'),
        ),
        migrations.AddField(
            model_name='stappconfpage',
            name='st_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='smartthings.STApp'),
        ),
        migrations.AddField(
            model_name='stapp',
            name='permissions',
            field=models.ManyToManyField(to='smartthings.STAppPermission'),
        ),
    ]
