# Generated by Django 2.0.8 on 2018-10-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0006_auto_20181012_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapp',
            name='app_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
