# Generated by Django 2.0.8 on 2018-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0008_auto_20181012_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapp',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', to='smartthings.STAppPermission'),
        ),
    ]
