# Generated by Django 2.0.8 on 2018-10-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0009_auto_20181012_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='component_id',
            field=models.CharField(default='main', max_length=36),
        ),
        migrations.AddField(
            model_name='stappinstance',
            name='location_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
