# Generated by Django 2.0.8 on 2018-10-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0011_auto_20181018_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stappconfsectionsetting',
            name='setting_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
