# Generated by Django 2.0.8 on 2018-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0012_auto_20181018_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stappconfsectionsetting',
            name='setting_id',
            field=models.CharField(default=None, max_length=36),
        ),
    ]
