# Generated by Django 2.0.8 on 2018-10-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0013_auto_20181018_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='STAppInstanceSettingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='component_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='device',
            name='st_app_instance',
        ),
        migrations.AddField(
            model_name='stappinstancesettingdevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartthings.Device'),
        ),
        migrations.AddField(
            model_name='stappinstancesettingdevice',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.STAppConfSectionSetting'),
        ),
        migrations.AddField(
            model_name='stappinstancesettingdevice',
            name='st_app_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartthings.STAppInstance'),
        ),
    ]
