# Generated by Django 2.0.8 on 2018-10-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0014_auto_20181019_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STAppInstanceSettingDevice',
            new_name='STAppInstanceSetting',
        ),
    ]
