# Generated by Django 2.0.8 on 2018-10-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0015_auto_20181019_1512'),
        ('smartthings', '0015_auto_20181018_2151'),
    ]

    operations = [
    ]
