# Generated by Django 2.0.8 on 2018-10-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0015_auto_20181019_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stappinstance',
            name='st_installed_app_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='stappinstancesetting',
            name='st_app_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_settings', to='smartthings.STAppInstance'),
        ),
    ]
