# Generated by Django 2.0.8 on 2018-10-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0016_auto_20181019_1618'),
        ('smartthings', '0016_merge_20181019_1610'),
    ]

    operations = [
    ]
