# Generated by Django 2.0.8 on 2018-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0019_auto_20181022_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapp',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stapp',
            name='client_secrete',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True),
        ),
    ]
