# Generated by Django 2.0.8 on 2018-10-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0021_auto_20181022_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stapp',
            old_name='client_secrete',
            new_name='client_secret',
        ),
    ]
