# Generated by Django 2.0.8 on 2018-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0022_auto_20181022_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='stapp',
            name='proj_endpoint',
            field=models.URLField(default=None, null=True),
        ),
    ]
