# Generated by Django 2.0.8 on 2018-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0023_stapp_proj_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stapp',
            name='proj_endpoint',
        ),
        migrations.AddField(
            model_name='stapp',
            name='debug_endpoint',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stapp',
            name='docker_endpoint',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stapp',
            name='prod_endpoint',
            field=models.URLField(default=None, null=True),
        ),
    ]
