# Generated by Django 2.0.8 on 2018-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0024_auto_20181125_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapp',
            name='debug_endpoint',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stapp',
            name='docker_endpoint',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='stapp',
            name='prod_endpoint',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
