# Generated by Django 2.0.8 on 2018-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0025_auto_20181125_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
