# Generated by Django 2.0.8 on 2019-03-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0026_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
