# Generated by Django 2.2 on 2019-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0029_project_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stapp',
            name='prod_endpoint',
            field=models.URLField(blank=True, default='https://api.superifttt.cs.uchicago.edu/', null=True),
        ),
    ]
