# Generated by Django 2.2 on 2019-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0032_auto_20190622_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stappconfpage',
            name='nextPageId',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stappconfpage',
            name='previousPageId',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
