# Generated by Django 2.2 on 2019-07-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartthings', '0033_auto_20190628_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='subscription',
            field=models.SlugField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='capability',
            name='st_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
